name: tests

on:
  push:
    
permissions:
  actions: read
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'      # Java 11 (LTS)
        distribution: 'temurin' # Eclipse Temurin
        cache: 'maven'          # Cache Maven dependencies
    - name: Run Unit Tests
      run: |
        mvn test
    - name: Publish Test Results
      if: ${{ always() }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: "**/TEST-*.xml"